/**
 * iPOD ROM seismic data for Salton Sea candidate sites.
 *
 * Generated by scripts/seismic_rom.py using the Scripps LOH dataset.
 * Source: Scripps Institution of Oceanography — loh.hdf5
 * Method: iPOD (interpolated Proper Orthogonal Decomposition) + RBF interpolation
 *
 * Earthquake ensemble: 500 scenarios
 *   depth  5–15 km | strike 310–330° | dip 75–90° | rake 160–180°
 *   (representative of Imperial Valley right-lateral seismicity)
 *
 * PGV values are at the p95 hazard level (95th percentile across scenarios).
 * Run `python scripts/seismic_rom.py --data loh.hdf5` to regenerate from source.
 */

import romResults from './seismic_rom_results.json'
import { ROMSeismicData } from '@/lib/types'

type RawSite = {
  pgv_mean_cm_s: number
  pgv_p50_cm_s: number
  pgv_p84_cm_s: number
  pgv_p95_cm_s: number
  pgv_max_cm_s: number
  n_scenarios: number
}

function toROMSeismicData(raw: RawSite): ROMSeismicData {
  return {
    pgvMeanCmS:  raw.pgv_mean_cm_s,
    pgvP50CmS:   raw.pgv_p50_cm_s,
    pgvP84CmS:   raw.pgv_p84_cm_s,
    pgvP95CmS:   raw.pgv_p95_cm_s,
    pgvMaxCmS:   raw.pgv_max_cm_s,
    nScenarios:  raw.n_scenarios,
  }
}

const raw = romResults.sites as Record<string, RawSite>

export const ROM_SEISMIC: Record<string, ROMSeismicData> = Object.fromEntries(
  Object.entries(raw).map(([id, site]) => [id, toROMSeismicData(site)])
)

export const ROM_META = {
  model:       romResults.model,
  source:      romResults.source_dataset,
  nTraining:   romResults.n_training,
  nScenarios:  romResults.n_scenarios,
  eqParams:    romResults.earthquake_params,
}
